# Generated by Django 3.1 on 2021-12-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20211211_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
